"""
blockchain_service.py
Handles all interactions with the DocumentVerifier smart contract via Web3.py.
"""

import os
import json
from pathlib import Path

from web3 import Web3
from web3.exceptions import ContractLogicError
from dotenv import load_dotenv

load_dotenv()

# ── Configuration ─────────────────────────────────────────────────────────────

RPC_URL           = os.getenv("RPC_URL", "http://127.0.0.1:8545")
CONTRACT_ADDRESS  = os.getenv("CONTRACT_ADDRESS", "")
PRIVATE_KEY       = os.getenv("PRIVATE_KEY", "")

# ABI file is generated by the deploy script (blockchain/scripts/deploy.js)
ABI_PATH = Path(__file__).parent.parent / "abi" / "DocumentVerifier.json"


# ── Web3 connection ───────────────────────────────────────────────────────────

def _get_web3() -> Web3:
    """Return a connected Web3 instance."""
    w3 = Web3(Web3.HTTPProvider(RPC_URL))
    if not w3.is_connected():
        raise ConnectionError(
            f"Cannot connect to blockchain node at {RPC_URL}. "
            "Make sure 'npx hardhat node' is running."
        )
    return w3


def _get_contract(w3: Web3):
    """Load and return the deployed contract instance."""
    if not CONTRACT_ADDRESS:
        raise ValueError(
            "CONTRACT_ADDRESS is not set. Deploy the contract first and add "
            "the address to backend/.env."
        )

    if not ABI_PATH.exists():
        raise FileNotFoundError(
            f"ABI file not found at {ABI_PATH}. "
            "Run 'npx hardhat run scripts/deploy.js' to generate it."
        )

    with open(ABI_PATH) as f:
        abi_data = json.load(f)

    abi = abi_data.get("abi", abi_data)  # handle both {abi:[...]} and [...]

    checksum_address = Web3.to_checksum_address(CONTRACT_ADDRESS)
    return w3.eth.contract(address=checksum_address, abi=abi)


def _get_account(w3: Web3):
    """Return the account derived from PRIVATE_KEY."""
    if not PRIVATE_KEY:
        raise ValueError(
            "PRIVATE_KEY is not set. Add a test wallet private key to backend/.env."
        )
    return w3.eth.account.from_key(PRIVATE_KEY)


def _send_transaction(w3: Web3, contract_function):
    """
    Sign and send a state-changing transaction.

    Args:
        w3:                Web3 instance.
        contract_function: A prepared contract function call
                           (e.g. contract.functions.registerDocument(...)).

    Returns:
        The transaction receipt.
    """
    account = _get_account(w3)

    tx = contract_function.build_transaction({
        "from":  account.address,
        "nonce": w3.eth.get_transaction_count(account.address),
        "gas":   300_000,
        "gasPrice": w3.eth.gas_price,
    })

    signed_tx = w3.eth.account.sign_transaction(tx, private_key=PRIVATE_KEY)
    # Web3.py <6 uses `rawTransaction`; >=6 uses `raw_transaction` — support both
    raw_tx    = getattr(signed_tx, "raw_transaction", None) or signed_tx.rawTransaction
    tx_hash   = w3.eth.send_raw_transaction(raw_tx)
    receipt   = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)

    return receipt


# ── Public API ────────────────────────────────────────────────────────────────

def register_document(document_id: str, cid: str) -> dict:
    """
    Call registerDocument() on the smart contract.

    Returns:
        dict with tx_hash and issuer address.

    Raises:
        RuntimeError on contract revert.
    """
    w3       = _get_web3()
    contract = _get_contract(w3)
    account  = _get_account(w3)

    try:
        fn      = contract.functions.registerDocument(document_id, cid)
        receipt = _send_transaction(w3, fn)
    except ContractLogicError as e:
        raise RuntimeError(f"Contract revert: {e}") from e

    return {
        "tx_hash": receipt.transactionHash.hex(),
        "issuer":  account.address,
        "status":  "success" if receipt.status == 1 else "failed",
    }


def verify_document(document_id: str, cid: str) -> bool:
    """
    Call verifyDocument() on the smart contract (read-only).

    Returns:
        True if the CID matches and the document is valid, False otherwise.

    Raises:
        RuntimeError if the document does not exist (contract reverts).
    """
    w3       = _get_web3()
    contract = _get_contract(w3)

    try:
        return contract.functions.verifyDocument(document_id, cid).call()
    except ContractLogicError as e:
        raise RuntimeError(f"Contract revert: {e}") from e


def get_document(document_id: str) -> dict:
    """
    Call getDocument() on the smart contract (read-only).

    Returns:
        dict with documentId, cid, issuer, timestamp, valid.

    Raises:
        RuntimeError if the document is not found.
    """
    w3       = _get_web3()
    contract = _get_contract(w3)

    try:
        doc_id, cid, issuer, timestamp, valid = (
            contract.functions.getDocument(document_id).call()
        )
    except ContractLogicError as e:
        raise RuntimeError(f"Contract revert: {e}") from e

    return {
        "documentId": doc_id,
        "cid":        cid,
        "issuer":     issuer,
        "timestamp":  timestamp,
        "valid":      valid,
    }


def revoke_document(document_id: str) -> dict:
    """
    Call revokeDocument() on the smart contract.

    Returns:
        dict with tx_hash.

    Raises:
        RuntimeError on contract revert.
    """
    w3       = _get_web3()
    contract = _get_contract(w3)

    try:
        fn      = contract.functions.revokeDocument(document_id)
        receipt = _send_transaction(w3, fn)
    except ContractLogicError as e:
        raise RuntimeError(f"Contract revert: {e}") from e

    return {
        "tx_hash": receipt.transactionHash.hex(),
        "status":  "success" if receipt.status == 1 else "failed",
    }
